version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  dj:
    container_name: dj
    build: django
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./django:/code
    ports:
      - "80:8080"
    depends_on:
      - db
  ng:
    container_name: ng
    build: angular
    ports:
      - "8000:80"